
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.
        


### Direct measurement of RSFOF 
class rSFOFDirect:

                class inclusive:
                        val = 1.092488
                        err = 0.046810
                        valMC = 1.101838
                        errMC = 0.044675
      
              

        

        
### New rMuE factorization

class rMuELeptonPt:

                class inclusive:
                        ptOffset = 1.355876
                        ptOffsetErr = 0.007509
                        ptFalling = 6.665050
                        ptFallingErr = 0.324844
                        etaParabolaBase = 0.647275
                        etaParabolaBaseErr = 0.001513
                        etaParabolaMinus = 0.461575
                        etaParabolaMinusErr = 0.023638
                        etaParabolaPlus = 0.689793
                        etaParabolaPlusErr = 0.026883
                        norm = 1.225792
                        normErr = 0.001342
                        
                        ptOffsetMC = 1.414833
                        ptOffsetErrMC = 0.012395
                        ptFallingMC = 4.110771
                        ptFallingErrMC = 0.528304
                        etaParabolaBaseMC = 0.657170
                        etaParabolaBaseErrMC = 0.002527
                        etaParabolaMinusMC = 0.206619
                        etaParabolaMinusErrMC = 0.035662
                        etaParabolaPlusMC = 0.313683
                        etaParabolaPlusErrMC = 0.037508
                        normMC = 1.226075
                        normErrMC = 0.001390
          



        

### rMuE for the old factorization method

class rMuE:

                class inclusive:
                        val = 1.224877
                        err = 0.122495
                        valMC = 1.226317
                        errMC = 0.122640
         



        

        
class rSFOFTrig:

                class inclusive:
                        val = 1.036942
                        err = 0.044289
                        valMC = 1.025277
                        errMC = 0.040852
      
        
        

        

        
### R_SFOF using the old factorization method
        
class rSFOFFactOld:                                   
        class inclusive:
                
                class SF:
                        val = 1.058347
                        err = 0.049919
                        valMC = 1.046688
                        errMC = 0.046723
      
                
                class EE:
                        val = 0.423284
                        err = 0.128300
                        valMC = 0.418031
                        errMC = 0.126838

                
                class MM:
                        val = 0.635063
                        err = 0.129884
                        valMC = 0.628657
                        errMC = 0.128210
      
        



        
### R_SFOF combination using the old factorization method

class rSFOF:

                class inclusive:
                        val = 1.073335
                        err = 0.037389
                        valMC = 1.075498
                        errMC = 0.032290
           

                                        

class rEEOF:

                class inclusive:
                        val = 0.448567
                        err = 0.020967
                        valMC = 0.451581
                        errMC = 0.018405
          
      


class rMMOF:

                class inclusive:
                        val = 0.642349
                        err = 0.042585
                        valMC = 0.648678
                        errMC = 0.025973
           
              



class triggerEffs:                                  
        class inclusive:
                
                class effEE:
                        val = 0.906308
                        err = 0.030187
                        valMC = 0.952273
                        errMC = 0.030017
      
                
                class effMM:
                        val = 0.873297
                        err = 0.030219
                        valMC = 0.946838
                        errMC = 0.030015

                
                class effEM:
                        val = 0.857955
                        err = 0.030132
                        valMC = 0.926142
                        errMC = 0.030005
              
        
        
              

