
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.
        


### Direct measurement of RSFOF 
class rSFOFDirect:

                class inclusive:
                        val = 1.093357
                        err = 0.045660
                        valMC = 1.092666
                        errMC = 0.044065
      
              

        

        
### New rMuE factorization

class rMuELeptonPt:

                class inclusive:
                        ptOffset = 1.492659
                        ptOffsetErr = 0.008420
                        ptFalling = 6.134574
                        ptFallingErr = 0.363669
                        etaParabolaBase = 0.600323
                        etaParabolaBaseErr = 0.001456
                        etaParabolaMinus = 0.355579
                        etaParabolaMinusErr = 0.021926
                        etaParabolaPlus = 0.476144
                        etaParabolaPlusErr = 0.023703
                        norm = 1.277481
                        normErr = 0.001458
                        
                        ptOffsetMC = 1.522244
                        ptOffsetErrMC = 0.010686
                        ptFallingMC = 5.790789
                        ptFallingErrMC = 0.457992
                        etaParabolaBaseMC = 0.592302
                        etaParabolaBaseErrMC = 0.001785
                        etaParabolaMinusMC = 0.432522
                        etaParabolaMinusErrMC = 0.030004
                        etaParabolaPlusMC = 0.461380
                        etaParabolaPlusErrMC = 0.028824
                        normMC = 1.284392
                        normErrMC = 0.001554
          



        

### rMuE for the old factorization method

class rMuE:

                class inclusive:
                        val = 1.275178
                        err = 0.127526
                        valMC = 1.283909
                        errMC = 0.128400
         



        

        
class rSFOFTrig:

                class inclusive:
                        val = 1.047892
                        err = 0.041795
                        valMC = 1.042808
                        errMC = 0.041111
      
        
        

        

        
### R_SFOF using the old factorization method
        
class rSFOFFactOld:                                   
        class inclusive:
                
                class SF:
                        val = 1.079005
                        err = 0.050139
                        valMC = 1.075542
                        errMC = 0.049914
      
                
                class EE:
                        val = 0.410881
                        err = 0.134635
                        valMC = 0.406107
                        errMC = 0.134851

                
                class MM:
                        val = 0.668125
                        err = 0.136265
                        valMC = 0.669435
                        errMC = 0.136473
      
        



        
### R_SFOF combination using the old factorization method

class rSFOF:

                class inclusive:
                        val = 1.086764
                        err = 0.033983
                        valMC = 1.085166
                        errMC = 0.033034
           

                                        

class rEEOF:

                class inclusive:
                        val = 0.410528
                        err = 0.023920
                        valMC = 0.420500
                        errMC = 0.016922
          
      


class rMMOF:

                class inclusive:
                        val = 0.681846
                        err = 0.035428
                        valMC = 0.671840
                        errMC = 0.026703
           
              



class triggerEffs:                                  
        class inclusive:
                
                class effEE:
                        val = 0.916102
                        err = 0.030183
                        valMC = 0.934199
                        errMC = 0.030010
      
                
                class effMM:
                        val = 0.948788
                        err = 0.030105
                        valMC = 0.979421
                        errMC = 0.030002

                
                class effEM:
                        val = 0.889692
                        err = 0.030111
                        valMC = 0.917276
                        errMC = 0.030003
              
        
        
              

