
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.
        


### Direct measurement of RSFOF 
class rSFOFDirect:

                class inclusive:
                        val = 1.052231
                        err = 0.044204
                        valMC = 1.068113
                        errMC = 0.043070
      
              

        

        
### New rMuE factorization

class rMuELeptonPt:

                class inclusive:
                        ptOffset = 1.437270
                        ptOffsetErr = 0.006269
                        ptFalling = 3.869983
                        ptFallingErr = 0.266410
                        etaParabolaBase = 0.653446
                        etaParabolaBaseErr = 0.001253
                        etaParabolaMinus = 0.096684
                        etaParabolaMinusErr = 0.015467
                        etaParabolaPlus = 0.098933
                        etaParabolaPlusErr = 0.015245
                        norm = 1.234357
                        normErr = 0.001111
                        
                        ptOffsetMC = 1.464001
                        ptOffsetErrMC = 0.012166
                        ptFallingMC = 3.270778
                        ptFallingErrMC = 0.517031
                        etaParabolaBaseMC = 0.643979
                        etaParabolaBaseErrMC = 0.002370
                        etaParabolaMinusMC = 0.242338
                        etaParabolaMinusErrMC = 0.032923
                        etaParabolaPlusMC = 0.171805
                        etaParabolaPlusErrMC = 0.031390
                        normMC = 1.240027
                        normErrMC = 0.001131
          



        

### rMuE for the old factorization method

class rMuE:

                class inclusive:
                        val = 1.233582
                        err = 0.123363
                        valMC = 1.239198
                        errMC = 0.123925
         



        

        
class rSFOFTrig:

                class inclusive:
                        val = 1.028784
                        err = 0.041750
                        valMC = 1.029436
                        errMC = 0.040514
      
        
        

        

        
### R_SFOF using the old factorization method
        
class rSFOFFactOld:                                   
        class inclusive:
                
                class SF:
                        val = 1.051535
                        err = 0.047899
                        valMC = 1.053201
                        errMC = 0.047043
      
                
                class EE:
                        val = 0.416990
                        err = 0.128037
                        valMC = 0.415364
                        errMC = 0.128616

                
                class MM:
                        val = 0.634545
                        err = 0.129500
                        valMC = 0.637837
                        errMC = 0.130019
      
        



        
### R_SFOF combination using the old factorization method

class rSFOF:

                class inclusive:
                        val = 1.051600
                        err = 0.045605
                        valMC = 1.061313
                        errMC = 0.031767
           

                                        

class rEEOF:

                class inclusive:
                        val = 0.418598
                        err = 0.072986
                        valMC = 0.434145
                        errMC = 0.017447
          
      


class rMMOF:

                class inclusive:
                        val = 0.633611
                        err = 0.086463
                        valMC = 0.633774
                        errMC = 0.025154
           
              



class triggerEffs:                                  
        class inclusive:
                
                class effEE:
                        val = 0.923209
                        err = 0.030114
                        valMC = 0.947647
                        errMC = 0.030019
      
                
                class effMM:
                        val = 0.924837
                        err = 0.030107
                        valMC = 0.953746
                        errMC = 0.030008

                
                class effEM:
                        val = 0.898169
                        err = 0.030075
                        valMC = 0.923507
                        errMC = 0.030006
              
        
        
              

