
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.



class rOutIn:
        class mass20To60:
                
                class inclusive:
                        val = 0.057262
                        err = 0.028694
                        valMC = 0.055020
                        errMC = 0.027569

        
        class mass60To86:
                
                class inclusive:
                        val = 0.117247
                        err = 0.058687
                        valMC = 0.110493
                        errMC = 0.055306

     
        class mass96To150:
                
                class inclusive:
                        val = 0.158782
                        err = 0.079457
                        valMC = 0.146692
                        errMC = 0.073408

                
        class mass150To200:
                
                class inclusive:
                        val = 0.015066
                        err = 0.015103
                        valMC = 0.014810
                        errMC = 0.014844

        
        class mass200To300:
                
                class inclusive:
                        val = 0.011206
                        err = 0.011247
                        valMC = 0.010373
                        errMC = 0.010413

        
        class mass300To400:
                
                class inclusive:
                        val = 0.003114
                        err = 0.003160
                        valMC = 0.004182
                        errMC = 0.004218

        
        class mass400:
                
                class inclusive:
                        val = 0.004759
                        err = 0.004791
                        valMC = 0.006758
                        errMC = 0.006790

        
      

