
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.



class rOutIn:
	class lowMass:
	
		class inclusive:
			val = 0.071878
			err = 0.018026
			valMC = 0.067403
			errMC = 0.016891

	
		class central:
			val = 0.076142
			err = 0.019131
			valMC = 0.070775
			errMC = 0.017762

	
		class forward:
			val = 0.064645
			err = 0.016297
			valMC = 0.061658
			errMC = 0.015510

	class highMass:
	
		class inclusive:
			val = 0.026862
			err = 0.006810
			valMC = 0.022727
			errMC = 0.005758

	
		class central:
			val = 0.025272
			err = 0.006463
			valMC = 0.020747
			errMC = 0.005308

	
		class forward:
			val = 0.029557
			err = 0.007652
			valMC = 0.026100
			errMC = 0.006728

	class aboveZ:
	
		class inclusive:
			val = 0.046798
			err = 0.011744
			valMC = 0.042142
			errMC = 0.010569

	
		class central:
			val = 0.044097
			err = 0.011098
			valMC = 0.041371
			errMC = 0.010397

	
		class forward:
			val = 0.051381
			err = 0.012955
			valMC = 0.043456
			errMC = 0.010949

	class belowZ:
	
		class inclusive:
			val = 0.036595
			err = 0.009198
			valMC = 0.035847
			errMC = 0.008999

	
		class central:
			val = 0.034336
			err = 0.008666
			valMC = 0.033755
			errMC = 0.008500

	
		class forward:
			val = 0.040427
			err = 0.010231
			valMC = 0.039412
			errMC = 0.009948

class rOutInEE:
	class lowMass:
	
		class inclusive:
			val = 0.066655
			err = 0.016784
			valMC = 0.059504
			errMC = 0.014966

	
		class central:
			val = 0.071150
			err = 0.017978
			valMC = 0.063584
			errMC = 0.016038

	
		class forward:
			val = 0.058209
			err = 0.014873
			valMC = 0.051692
			errMC = 0.013159

	class highMass:
	
		class inclusive:
			val = 0.028691
			err = 0.007344
			valMC = 0.023759
			errMC = 0.006083

	
		class central:
			val = 0.026553
			err = 0.006890
			valMC = 0.023025
			errMC = 0.005962

	
		class forward:
			val = 0.032708
			err = 0.008687
			valMC = 0.025164
			errMC = 0.006734

	class aboveZ:
	
		class inclusive:
			val = 0.044533
			err = 0.011231
			valMC = 0.036240
			errMC = 0.009136

	
		class central:
			val = 0.040119
			err = 0.010185
			valMC = 0.036429
			errMC = 0.009225

	
		class forward:
			val = 0.052826
			err = 0.013471
			valMC = 0.035878
			errMC = 0.009181

	class belowZ:
	
		class inclusive:
			val = 0.037844
			err = 0.009566
			valMC = 0.036712
			errMC = 0.009259

	
		class central:
			val = 0.036465
			err = 0.009279
			valMC = 0.036853
			errMC = 0.009337

	
		class forward:
			val = 0.040435
			err = 0.010398
			valMC = 0.036443
			errMC = 0.009342

class rOutInMM:
	class lowMass:
	
		class inclusive:
			val = 0.075314
			err = 0.018919
			valMC = 0.073140
			errMC = 0.018349

	
		class central:
			val = 0.079555
			err = 0.020046
			valMC = 0.076384
			errMC = 0.019207

	
		class forward:
			val = 0.068627
			err = 0.017365
			valMC = 0.068054
			errMC = 0.017158

	class highMass:
	
		class inclusive:
			val = 0.025090
			err = 0.006423
			valMC = 0.021934
			errMC = 0.005598

	
		class central:
			val = 0.023874
			err = 0.006208
			valMC = 0.018920
			errMC = 0.004926

	
		class forward:
			val = 0.027007
			err = 0.007143
			valMC = 0.026660
			errMC = 0.006936
	
	class aboveZ:
	
		class inclusive:
			val = 0.048350
			err = 0.012161
			valMC = 0.046442
			errMC = 0.011665

	
		class central:
			val = 0.047072
			err = 0.011893
			valMC = 0.045241
			errMC = 0.011402

	
		class forward:
			val = 0.050365
			err = 0.012767
			valMC = 0.048325
			errMC = 0.012214
	
	class belowZ:
	
		class inclusive:
			val = 0.035541
			err = 0.008967
			valMC = 0.035202
			errMC = 0.008861

	
		class central:
			val = 0.032516
			err = 0.008269
			valMC = 0.031307
			errMC = 0.007931

	
		class forward:
			val = 0.040310
			err = 0.010271
			valMC = 0.041311
			errMC = 0.010472
	
	


	

class rMuE:

		class inclusive:
			val = 1.170707
			err = 0.117159
			valMC = 1.176768
			errMC = 0.117746
	

		class central:
			val = 1.135150
			err = 0.113650
			valMC = 1.132300
			errMC = 0.113334


		class forward:
			val = 1.234169
			err = 0.246961
			valMC = 1.258103
			errMC = 0.251723
	



	

	
class rSFOFTrig:

		class central:
			val = 0.999963
			err = 0.072326
			valMC = 1.027329
			errMC = 0.066369
	

		class forward:
			val = 1.063600
			err = 0.091489
			valMC = 1.029271
			errMC = 0.071659


		class inclusive:
			val = 1.017078
			err = 0.071684
			valMC = 1.027891
			errMC = 0.067787

	
	

	

	
class rSFOFFact:
	class central:
		
		class SF:
			val = 1.008008
			err = 0.074010
			valMC = 1.035270
			errMC = 0.068097
	
		
		class EE:
			val = 0.440454
			err = 0.118027
			valMC = 0.453647
			errMC = 0.120063

		
		class MM:
			val = 0.567554
			err = 0.120833
			valMC = 0.581622
			errMC = 0.122344
		
	class forward:
		
		class SF:
			val = 1.087228
			err = 0.103832
			valMC = 1.056521
			errMC = 0.087670
	
		
		class EE:
			val = 0.430897
			err = 0.265270
			valMC = 0.409057
			errMC = 0.260652

		
		class MM:
			val = 0.656331
			err = 0.268667
			valMC = 0.647464
			errMC = 0.262983
					
	class inclusive:
		
		class SF:
			val = 1.029736
			err = 0.074342
			valMC = 1.041538
			errMC = 0.070715
	
		
		class EE:
			val = 0.434386
			err = 0.123030
			valMC = 0.436743
			errMC = 0.124410

		
		class MM:
			val = 0.595350
			err = 0.126332
			valMC = 0.604795
			errMC = 0.127432
	
	

	

class rSFOF:

		class central:
			val = 1.032028
			err = 0.046433
			valMC = 1.048413
			errMC = 0.013107
	

		class forward:
			val = 1.091991
			err = 0.067859
			valMC = 1.079049
			errMC = 0.020358


		class inclusive:
			val = 1.052882
			err = 0.041297
			valMC = 1.058440
			errMC = 0.011107
	



class rEEOF:

		class central:
			val = 0.426602
			err = 0.032048
			valMC = 0.449919
			errMC = 0.007287
	

		class forward:
			val = 0.457564
			err = 0.051269
			valMC = 0.435888
			errMC = 0.011178


		class inclusive:
			val = 0.436176
			err = 0.027396
			valMC = 0.445370
			errMC = 0.006116
	

					

class rMMOF:

		class central:
			val = 0.616198
			err = 0.039807
			valMC = 0.599582
			errMC = 0.009295
	

		class forward:
			val = 0.637937
			err = 0.060836
			valMC = 0.642730
			errMC = 0.014799


		class inclusive:
			val = 0.624698
			err = 0.033676
			valMC = 0.613611
			errMC = 0.007904
	
	



class triggerEffs:
	class central:
		
		class effEE:
			val = 0.944994
			err = 0.050741
			valMC = 0.943159
			errMC = 0.050020
	
		
		class effMM:
			val = 0.928571
			err = 0.051945
			valMC = 0.938215
			errMC = 0.050033

		
		class effEM:
			val = 0.936782
			err = 0.055571
			valMC = 0.915660
			errMC = 0.050015
		
	class forward:
		
		class effEE:
			val = 0.959732
			err = 0.052166
			valMC = 0.929648
			errMC = 0.050064
	
		
		class effMM:
			val = 0.924686
			err = 0.054296
			valMC = 0.926712
			errMC = 0.050085

		
		class effEM:
			val = 0.885714
			err = 0.071795
			valMC = 0.901782
			errMC = 0.050042
					
	class inclusive:
		
		class effEE:
			val = 0.948633
			err = 0.050511
			valMC = 0.939473
			errMC = 0.050015
	
		
		class effMM:
			val = 0.927247
			err = 0.051235
			valMC = 0.934577
			errMC = 0.050024

		
		class effEM:
			val = 0.922131
			err = 0.054289
			valMC = 0.911596
			errMC = 0.050011
		
	
	
		

