
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.



class rOutIn:
        class mass20To60:
                
                class inclusive:
                        val = 0.057731
                        err = 0.028998
                        valMC = 0.055976
                        errMC = 0.028104

        
        class mass60To86:
                
                class inclusive:
                        val = 0.123424
                        err = 0.061847
                        valMC = 0.107585
                        errMC = 0.053909

     
        class mass96To150:
                
                class inclusive:
                        val = 0.153746
                        err = 0.077013
                        valMC = 0.143093
                        errMC = 0.071669

                
        class mass150To200:
                
                class inclusive:
                        val = 0.016005
                        err = 0.016080
                        valMC = 0.015671
                        errMC = 0.015736

        
        class mass200To300:
                
                class inclusive:
                        val = 0.010005
                        err = 0.010104
                        valMC = 0.009637
                        errMC = 0.009714

        
        class mass300To400:
                
                class inclusive:
                        val = 0.002930
                        err = 0.003023
                        valMC = 0.003158
                        errMC = 0.003233

        
        class mass400:
                
                class inclusive:
                        val = 0.004847
                        err = 0.004908
                        valMC = 0.006261
                        errMC = 0.006325

        
      

        


### Direct measurement of RSFOF 
class rSFOFDirect:

                class inclusive:
                        val = 1.104579
                        err = 0.045262
                        valMC = 1.076666
                        errMC = 0.043304
      
              

        

        
### New rMuE factorization

class rMuELeptonPt:

                class inclusive:
                        offset = 1.200577
                        offsetErr = 0.002544
                        falling = 1.533004
                        fallingErr = 0.106846
                        
                        offsetMC = 1.207062
                        offsetErrMC = 0.004940
                        fallingMC = 1.305799
                        fallingErrMC = 0.207505
          



        

### rMuE for the old factorization method

class rMuE:

                class inclusive:
                        val = 1.234007
                        err = 0.123406
                        valMC = 1.235490
                        errMC = 0.123555
         



        

        
class rSFOFTrig:

                class inclusive:
                        val = 1.028463
                        err = 0.041731
                        valMC = 1.024717
                        errMC = 0.040443
      
        
        

        

        
### R_SFOF using the old factorization method
        
class rSFOFFactOld:                                   
        class inclusive:
                
                class SF:
                        val = 1.051283
                        err = 0.047898
                        valMC = 1.047715
                        errMC = 0.046760
      
                
                class EE:
                        val = 0.416717
                        err = 0.128040
                        valMC = 0.414701
                        errMC = 0.127662

                
                class MM:
                        val = 0.634566
                        err = 0.129504
                        valMC = 0.633014
                        errMC = 0.129050
      
        



        
### R_SFOF combination using the old factorization method

class rSFOF:

                class inclusive:
                        val = 1.076949
                        err = 0.034487
                        valMC = 1.063300
                        errMC = 0.031772
           

                                        

class rEEOF:

                class inclusive:
                        val = 0.438718
                        err = 0.019517
                        valMC = 0.426052
                        errMC = 0.017130
          
      


class rMMOF:

                class inclusive:
                        val = 0.663332
                        err = 0.033066
                        valMC = 0.649718
                        errMC = 0.025664
           
              



class triggerEffs:                                  
        class inclusive:
                
                class effEE:
                        val = 0.923868
                        err = 0.030113
                        valMC = 0.946142
                        errMC = 0.030054
      
                
                class effMM:
                        val = 0.924500
                        err = 0.030108
                        valMC = 0.952677
                        errMC = 0.030020

                
                class effEM:
                        val = 0.898607
                        err = 0.030074
                        valMC = 0.926504
                        errMC = 0.030012
              
        
        
              

