
### central config file for all correction factors used in the dilepton edge search. This file was autogenerated.



class rOutIn:
        class mass20To60:
                
                class inclusive:
                        val = 0.059251
                        err = 0.029917
                        valMC = 0.054850
                        errMC = 0.027735

        
        class mass60To86:
                
                class inclusive:
                        val = 0.111746
                        err = 0.056166
                        valMC = 0.111092
                        errMC = 0.055859

     
        class mass96To150:
                
                class inclusive:
                        val = 0.155586
                        err = 0.078108
                        valMC = 0.149585
                        errMC = 0.075120

                
        class mass150To200:
                
                class inclusive:
                        val = 0.014023
                        err = 0.014208
                        valMC = 0.013771
                        errMC = 0.013956

        
        class mass200To300:
                
                class inclusive:
                        val = 0.011478
                        err = 0.011661
                        valMC = 0.006920
                        errMC = 0.007161

        
        class mass300To400:
                
                class inclusive:
                        val = 0.003274
                        err = 0.003491
                        valMC = 0.005051
                        errMC = 0.005233

        
        class mass400:
                
                class inclusive:
                        val = 0.005944
                        err = 0.006085
                        valMC = 0.008445
                        errMC = 0.008605

        
      

        


### Direct measurement of RSFOF 
class rSFOFDirect:

                class inclusive:
                        val = 1.104984
                        err = 0.046126
                        valMC = 1.091780
                        errMC = 0.043943
      
              

        

        
### New rMuE factorization

class rMuELeptonPt:

                class inclusive:
                        offset = 1.226410
                        offsetErr = 0.003395
                        falling = 2.789423
                        fallingErr = 0.144467
                        
                        offsetMC = 1.220192
                        offsetErrMC = 0.007290
                        fallingMC = 2.186998
                        fallingErrMC = 0.307657
          



        

### rMuE for the old factorization method

class rMuE:

                class inclusive:
                        val = 1.288579
                        err = 0.128865
                        valMC = 1.323587
                        errMC = 0.132368
         



        

        
class rSFOFTrig:

                class inclusive:
                        val = 1.052268
                        err = 0.041098
                        valMC = 1.044863
                        errMC = 0.040975
      
        
        

        

        
### R_SFOF using the old factorization method
        
class rSFOFFactOld:                                   
        class inclusive:
                
                class SF:
                        val = 1.086270
                        err = 0.050272
                        valMC = 1.086193
                        errMC = 0.051916
      
                
                class EE:
                        val = 0.408305
                        err = 0.136535
                        valMC = 0.394709
                        errMC = 0.139170

                
                class MM:
                        val = 0.677965
                        err = 0.138162
                        valMC = 0.691484
                        errMC = 0.140939
      
        



        
### R_SFOF combination using the old factorization method

class rSFOF:

                class inclusive:
                        val = 1.096374
                        err = 0.034099
                        valMC = 1.089448
                        errMC = 0.033541
           

                                        

class rEEOF:

                class inclusive:
                        val = 0.411262
                        err = 0.020370
                        valMC = 0.397158
                        errMC = 0.015981
          
      


class rMMOF:

                class inclusive:
                        val = 0.692966
                        err = 0.028954
                        valMC = 0.694472
                        errMC = 0.027484
           
              



class triggerEffs:                                  
        class inclusive:
                
                class effEE:
                        val = 0.959066
                        err = 0.030055
                        valMC = 0.958153
                        errMC = 0.030020
      
                
                class effMM:
                        val = 0.946222
                        err = 0.030096
                        valMC = 0.979588
                        errMC = 0.030007

                
                class effEM:
                        val = 0.905304
                        err = 0.030565
                        valMC = 0.927213
                        errMC = 0.030001
              
        
        
              

